system:
  preferredShell: PowerShell
  shellCommandExecutionEnabled: true
  description: ""

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    net.grayfallstown: DEBUG
    org.springdoc: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

projectsDir: C:\Users\mk\IdeaProjects\java\myprojects\chatgpt-file-and-command-center\projects\

#
#project:
#  dir: C:\Users\mk\IdeaProjects\java\myprojects\chatgpt-file-and-command-center\sampleproject
#  workingDir: C:\Users\mk\IdeaProjects\java\myprojects\chatgpt-file-and-command-center\sampleproject\workingdir
#  systemDescription: ""
