management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: grayfallstown

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    net.grayfallstown: DEBUG
    org.springdoc: DEBUG
  file:
    path: ./logs/chatgpt-command-and-control-center.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
  logback:
    configuration: classpath:logback-spring.xml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  server:
    url: http://grayfallstown.ddns.net:8080

projectsDir: C:\Users\mk\IdeaProjects\java\myprojects\chatgpt-file-and-command-center\projects\

#
#project:
#  dir: C:\Users\mk\IdeaProjects\java\myprojects\chatgpt-file-and-command-center\sampleproject
#  workingDir: C:\Users\mk\IdeaProjects\java\myprojects\chatgpt-file-and-command-center\sampleproject\workingdir
#  systemDescription: ""
