system:
  preferredShell: PowerShell
  shellCommandExecutionEnabled: true
  description: ""

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: grayfallstown

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    net.grayfallstown: DEBUG
    org.springdoc: DEBUG
    org.springframework.web: DEBUG  # Add this line to log web requests

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  server:
    url: http://grayfallstown.ddns.net:8080

projectsDir: C:\Users\mk\IdeaProjects\java\myprojects\chatgpt-file-and-command-center\projects\

#
#project:
#  dir: C:\Users\mk\IdeaProjects\java\myprojects\chatgpt-file-and-command-center\sampleproject
#  workingDir: C:\Users\mk\IdeaProjects\java\myprojects\chatgpt-file-and-command-center\sampleproject\workingdir
#  systemDescription: ""
